const Ruleset = {

  /*
  * Tune the weights for accuracy
  */
  weight: {
    char: 1,
    word: 1.3,
    segment: 1,
    rule: 1,
  },

  /*
  * List of supported languages (supported in some capacity)
  */
  languageList: ['fr', 'en', 'de', 'it', 'da', 'fi', 'es', 'r', 'nl', 'pt',
                 'no', 'tr', 'sv', 'ro', 'pl'],

  /*
  * Full alphabet for each language
  */
  alphabets: {
    no: 'ABCDEFGHIJKLMNOPQRSTUVWXYZÆØÅabcdefghijklmnopqrstuvwxyzæøå',
    sv: 'ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäö',
    fi: 'ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäö',
    da: 'ABCDEFGHIJKLMNOPQRSTUVWXYZÆØÅabcdefghijklmnopqrstuvwxyzæøå',
    en: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
    de: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄäÖöÜüß',
    nl: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
    pt: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzáâãàçéêíóôõú',
    es: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzñ',
    fr: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàâîïûéèêôùÿ',
    it: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
    pl: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzŁńśź',
    tr: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzığş',
    ro: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzășț',
    ru: 'АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛл†МмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя',
  },

  /*
  * 
  */
  wordRules: {
    es: [
      /\wtas?\b/g, // match ta or tas word ending
      /\wtos?\b/g, // match to or tos word ending
      /\wrros?\b/g, // match rros word ending
      /hi[a|e|i|o|u]/g, // match 'hi' followed by a vowel
    ],
    de: [
      /\wen\b/g, // match 'en' word ending
    ],
  },

  /*
  * List of common word segments in each language
  */
  wordSegments: {
    es: ['g', 'gü', 'hi', 'h', 'll', 'que', 'qui', 'rr'],
    nl: ['ij', 'ik'],
    da: ['tak'],
    en: ['th', 'ough'],
    fr: ['q', 'aie', 'ea', 'oix'],
    de: ['ie', 'dsch', 'ig', 'ich', 'ei'],
    pl: ['czy'],
  },

  /*
  * Combined list of pronouns, prepositions and conjunctions
  */
  words: {
    de: [
      'über',
      'oben',
      'nach',
      'gegen',
      'unter',
      'um',
      'wie',
      'bei',
      'vor',
      'hinter',
      'unten',
      'unter',
      'neben',
      'zwischen',
      'darüber hinaus',
      'aber',
      'durch',
      'trotz',
      'nach unten',
      'während',
      'ausgenommen',
      'für',
      'von',
      'in',
      'innen',
      'in',
      'in der Nähe von',
      'nächste',
      'von',
      'auf',
      'gegenüber',
      'heraus',
      'außerhalb',
      'pro',
      'plus',
      'um',
      'seit',
      'als',
      'durch',
      'bis',
      'z',
      'gegen',
      'unter',
      'im Gegensatz z',
      'bis',
      'hinauf',
      'durch',
      'mit',
      'innerhalb',
      'ohne',
      'zwei Wörter',
      'gemäß',
      'wegen',
      'nahe an',
      'durch',
      'bis auf',
      'weit entfernt',
      'innerhalb',
      'statt',
      'in der Nähe von',
      'neben',
      'außerhalb von',
      'vor',
      'drei Wörter',
      'soweit',
      'sowie',
      'zusätzlich z',
      'vor',
      'trotz',
      'im Namen von',
      'oben auf',
      'ueber',
      'darueber hinaus',
      'fuer',
      'gegenueber',
      'ich',
      'mich',
      'mir',
      'meiner',
      'mein',
      'd',
      'dich',
      'dir',
      'deiner',
      'dein',
      'er',
      'ihn',
      'ihm',
      'seiner',
      'sein',
      'es',
      'es',
      'ihm',
      'seiner',
      'sein',
      'sie',
      'ihr',
      'ihrer',
      'wir',
      'uns',
      'unser',
      'ihr',
      'euch',
      'euch',
      'euer',
      'euer',
      'sie',
      'ihnen',
      'ihrer',
      'ihr',
      'sie',
      'ihnen',
      'ihrer',
      'ihr',
      'aber',
      'beziehungsweise',
      'denn',
      'oder',
      'sondern',
      'und',
      'als',
      'bevor',
      'bis',
      'dass',
      'damit',
      'nachdem',
      'ob',
      'if',
      'obwohl',
      'seitdem',
      'sobald',
      'sofern',
      'as',
      'soweit',
      'sowie',
      'während',
      'weil',
      'wenn',
      'wie',
      'wo',
    ],

    es: [
      'a',
      'ante',
      'alrededor de',
      'bajo',
      'con',
      'contra',
      'de',
      'desde',
      'debajo de',
      'en',
      'entre',
      'encima de',
      'frente a',
      'fuera de',
      'hacia',
      'hasta',
      'por',
      'detrás de',
      'según',
      'sin',
      'sobre',
      'tras',
      'para',
      'yo',
      'me',
      'mío',
      'míos',
      'mía',
      'mías',
      'mí',
      'conmigo',
      'tú',
      'te',
      'tuyo',
      'tuyos',
      'tuya',
      'tuyas',
      'ti',
      'contigo',
      'vos',
      'con vos',
      'usted',
      'lo',
      'la',
      'se',
      'le',
      'se',
      'suyo',
      'suyos',
      'suya',
      'suyas',
      'usted',
      'con usted',
      'él',
      'ella',
      'ello',
      'él',
      'ella',
      'ello',
      'sí',
      'con él',
      'ella',
      'ello',
      'consigo',
      'nosotros',
      'nosotras',
      'nos',
      'nuestro',
      'nuestros',
      'nuestra',
      'nuestras',
      'nosotros',
      'nosotras',
      'con nosotros',
      'nosotras',
      'vosotros',
      'vosotras',
      'os',
      'vuestro',
      'vuestros',
      'vuestra',
      'vuestras',
      'vosotros',
      'vosotras',
      'con vosotros',
      'vosotras',
      'ustedes',
      'los',
      'las',
      'se',
      'les',
      'se',
      'suyo',
      'suyos',
      'suya',
      'suyas',
      'ustedes',
      'con ustedes',
      'ellos',
      'ellas',
      'ellos',
      'ellas',
      'sí',
      'con ellos',
      'ellas',
      'consigo',
      'y',
      'e',
      'ni',
      'o',
      '',
      'o bien',
      'pero',
      'mas',
      'aunque',
      'sin embargo',
      'no obstante',
      'por lo demás',
      'excepto',
      'es decir',
      'esto es',
      'porque',
      'pues',
      'puesto que',
      'ya que',
      'si',
      'con tal de que',
      'siempre que',
      'como',
    ],

    en: [
      'aboard',
      'about',
      'above',
      'absent',
      'across',
      'cross',
      'after',
      'against',
      'along',
      'alongside',
      'amid',
      'amidst',
      'among',
      'amongst',
      'apropos',
      'apud',
      'around',
      'round',
      'as',
      'astride',
      'at',
      'atop',
      'bar',
      'before',
      'afore',
      'B4',
      'behind',
      'ahind',
      'below',
      'ablow',
      'beneath',
      'beside',
      'besides',
      'between',
      'atween',
      'beyond',
      'ayond',
      'but',
      'by',
      'chez',
      'circa',
      'come',
      'dehors',
      'despite',
      'spite',
      'down',
      'during',
      'except',
      'for',
      'from',
      'in',
      'inside',
      'into',
      'less',
      'like',
      'minus',
      'near',
      'nearer',
      'anear',
      'notwithstanding',
      'of',
      'off',
      'on',
      'onto',
      'opposite',
      'out',
      'outen',
      'outside',
      'over',
      'pace',
      'past',
      'per',
      'plus',
      'post',
      'pre',
      'pro',
      'qua',
      're',
      'sans',
      'save',
      'sauf',
      'short',
      'since',
      'sithence',
      'than',
      'through',
      'thr',
      'throughout',
      'thruout',
      'till',
      'to',
      'toward',
      'under',
      'underneath',
      'unlike',
      'until',
      'til',
      'unto',
      'up',
      'upon',
      'upside',
      'versus',
      'via',
      'vice',
      'with',
      'within',
      'without',
      'worth',
      'I',
      'yo',
      'he',
      'she',
      'it',
      'we',
      'they',
      'me',
      'him',
      'her',
      'us',
      'them',
      'I',
      'yo',
      'he',
      'she',
      'it',
      'we',
      'they',
      'what',
      'who',
      'me',
      'him',
      'her',
      'it',
      'us',
      'yo',
      'them',
      'whom',
      'mine',
      'yours',
      'his',
      'hers',
      'ours',
      'theirs',
      'this',
      'that',
      'these',
      'those',
      'who',
      'whom',
      'which',
      'what',
      'whose',
      'whoever',
      'whatever',
      'whichever',
      'whomever',
      'who',
      'whom',
      'whose',
      'which',
      'that',
      'what',
      'whatever',
      'whoever',
      'whomever',
      'whichever',
      'myself',
      'yourself',
      'himself',
      'herself',
      'itself',
      'ourselves',
      'themselves',
      'Each',
      'other',
      'one',
      'another',
      'Anything',
      'everybody',
      'another',
      'each',
      'few',
      'many',
      'none',
      'some',
      'all',
      'any',
      'anybody',
      'anyone',
      'everyone',
      'everything',
      'no',
      'one',
      'nobody',
      'nothing',
      'none',
      'other',
      'others',
      'several',
      'somebody',
      'someone',
      'something',
      'most',
      'enough',
      'little',
      'more',
      'both',
      'either',
      'neither',
      'one',
      'much',
      'such',
      'and',
      'or',
      'but',
      'nor',
      'so',
      'for',
      'yet',
      'after',
      'although',
      'as',
      'as if',
      'as long as',
      'because',
      'before',
      'even if',
      'even though',
      'once',
      'since',
      'so that',
      'though',
      'till',
      'unless',
      'until',
      'what',
      'when',
      'whenever',
      'wherever',
      'whether',
      'while',
    ],
  },
}

module.exports = Ruleset;